[package]
name = "common-debug"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []
debug-dev = ["env_logger"]

[dependencies]
log = { workspace = true }
env_logger = { version = "0.11", optional = true }
